on:
   push:
   workflow_dispatch:
   
env:  
  containerhost: https://ghcr.io
   
jobs:

  build-test-image:
    strategy:
      matrix: 
        include:
        - dockerfile: Dockerfile
          containertag: ghcr.io/rajbos/testing-snyk

        - dockerfile: Dockerfile-runtime
          containertag: ghcr.io/rajbos/testing-runtime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
       
      - name: Build the Docker image
        run: docker build -t $containertag --pull .
        
      - name: Setup GitHub Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login $containerhost -u ${{ github.actor }} --password-stdin

      - name: Push to GitHub Container Registry
        run:  docker push $containertag
        
      - name: Cleanup GitHub Container Registry login data
        run: docker logout $containerhost
      
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: rajbos-actions/snyk-actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=Dockerfile
          image: ${{ env.containertag }}
        continue-on-error: true

      - name: Upload Snyk scan result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
